#!/bin/bash

mkdir -p keys certs reqs
chmod 700 keys

openssl req -new -x509 -days 3650 -newkey rsa:2048 -keyout keys/ca.key -outform PEM -out certs/ca.crt -subj '/C=US/ST=Illinois/L=Chicago/CN=TestCA/OU=Development' -sha256
chmod 600 keys/ca.key
